// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/entity.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "common/entity.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace bundle {
class ValueDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Value> {
} _Value_default_instance_;
class Entity_ValuesEntryDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Entity::Entity_ValuesEntry> {
} _Entity_ValuesEntry_default_instance_;
class EntityDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Entity> {
} _Entity_default_instance_;

namespace protobuf_common_2fentity_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_s8_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_u8_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_s32_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_u32_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_s64_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_u64_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_bool_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_float_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_double_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_string_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_bytes_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Value, value_datetime_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, values_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Value)},
  { 18, -1, sizeof(Entity)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Value_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Entity_ValuesEntry_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Entity_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "common/entity.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
file_level_metadata[1].reflection = Entity::Entity_ValuesEntry::CreateReflection(file_level_metadata[1].descriptor, _Entity_ValuesEntry_default_instance_.get_mutable());
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace

void TableStruct::Shutdown() {
  _Value_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Entity_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Value_default_instance_.DefaultConstruct();
  _Entity_ValuesEntry_default_instance_.DefaultConstruct();
  _Entity_default_instance_.DefaultConstruct();
  _Entity_ValuesEntry_default_instance_.get_mutable()->set_default_instance(_Entity_ValuesEntry_default_instance_.get_mutable());
  _Entity_ValuesEntry_default_instance_.get_mutable()->InitAsDefaultInstance();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\023common/entity.proto\022\006bundle\"\344\003\n\005Value\022"
      "%\n\004type\030\001 \001(\0162\027.bundle.Value.ValueType\022\020"
      "\n\010value_s8\030\002 \001(\021\022\020\n\010value_u8\030\003 \001(\r\022\021\n\tva"
      "lue_s32\030\004 \001(\021\022\021\n\tvalue_u32\030\005 \001(\r\022\021\n\tvalu"
      "e_s64\030\006 \001(\022\022\021\n\tvalue_u64\030\007 \001(\004\022\022\n\nvalue_"
      "bool\030\010 \001(\010\022\023\n\013value_float\030\t \001(\002\022\024\n\014value"
      "_double\030\n \001(\001\022\024\n\014value_string\030\013 \001(\t\022\023\n\013v"
      "alue_bytes\030\014 \001(\014\022\026\n\016value_datetime\030\r \001(\t"
      "\"\301\001\n\tValueType\022\013\n\007type_s8\020\000\022\013\n\007type_u8\020\001"
      "\022\014\n\010type_s32\020\002\022\014\n\010type_u32\020\003\022\014\n\010type_s64"
      "\020\004\022\014\n\010type_u64\020\005\022\r\n\ttype_bool\020\006\022\016\n\ntype_"
      "float\020\007\022\017\n\013type_double\020\010\022\017\n\013type_string\020"
      "\t\022\016\n\ntype_bytes\020\n\022\021\n\rtype_datetime\020\013\"~\n\006"
      "Entity\022\n\n\002id\030\001 \001(\004\022*\n\006values\030\002 \003(\0132\032.bun"
      "dle.Entity.ValuesEntry\032<\n\013ValuesEntry\022\013\n"
      "\003key\030\001 \001(\t\022\034\n\005value\030\002 \001(\0132\r.bundle.Value"
      ":\0028\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 652);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "common/entity.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_common_2fentity_2eproto

const ::google::protobuf::EnumDescriptor* Value_ValueType_descriptor() {
  protobuf_common_2fentity_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_common_2fentity_2eproto::file_level_enum_descriptors[0];
}
bool Value_ValueType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Value_ValueType Value::type_s8;
const Value_ValueType Value::type_u8;
const Value_ValueType Value::type_s32;
const Value_ValueType Value::type_u32;
const Value_ValueType Value::type_s64;
const Value_ValueType Value::type_u64;
const Value_ValueType Value::type_bool;
const Value_ValueType Value::type_float;
const Value_ValueType Value::type_double;
const Value_ValueType Value::type_string;
const Value_ValueType Value::type_bytes;
const Value_ValueType Value::type_datetime;
const Value_ValueType Value::ValueType_MIN;
const Value_ValueType Value::ValueType_MAX;
const int Value::ValueType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Value::kTypeFieldNumber;
const int Value::kValueS8FieldNumber;
const int Value::kValueU8FieldNumber;
const int Value::kValueS32FieldNumber;
const int Value::kValueU32FieldNumber;
const int Value::kValueS64FieldNumber;
const int Value::kValueU64FieldNumber;
const int Value::kValueBoolFieldNumber;
const int Value::kValueFloatFieldNumber;
const int Value::kValueDoubleFieldNumber;
const int Value::kValueStringFieldNumber;
const int Value::kValueBytesFieldNumber;
const int Value::kValueDatetimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Value::Value()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_common_2fentity_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:bundle.Value)
}
Value::Value(const Value& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value_string().size() > 0) {
    value_string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_string_);
  }
  value_bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value_bytes().size() > 0) {
    value_bytes_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_bytes_);
  }
  value_datetime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value_datetime().size() > 0) {
    value_datetime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_datetime_);
  }
  ::memcpy(&type_, &from.type_,
    reinterpret_cast<char*>(&value_float_) -
    reinterpret_cast<char*>(&type_) + sizeof(value_float_));
  // @@protoc_insertion_point(copy_constructor:bundle.Value)
}

void Value::SharedCtor() {
  value_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_datetime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&type_, 0, reinterpret_cast<char*>(&value_float_) -
    reinterpret_cast<char*>(&type_) + sizeof(value_float_));
  _cached_size_ = 0;
}

Value::~Value() {
  // @@protoc_insertion_point(destructor:bundle.Value)
  SharedDtor();
}

void Value::SharedDtor() {
  value_string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_bytes_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_datetime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Value::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Value::descriptor() {
  protobuf_common_2fentity_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_common_2fentity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Value& Value::default_instance() {
  protobuf_common_2fentity_2eproto::InitDefaults();
  return *internal_default_instance();
}

Value* Value::New(::google::protobuf::Arena* arena) const {
  Value* n = new Value;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Value::Clear() {
// @@protoc_insertion_point(message_clear_start:bundle.Value)
  value_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_bytes_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_datetime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&type_, 0, reinterpret_cast<char*>(&value_float_) -
    reinterpret_cast<char*>(&type_) + sizeof(value_float_));
}

bool Value::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bundle.Value)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .bundle.Value.ValueType type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::bundle::Value_ValueType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 value_s8 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &value_s8_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 value_u8 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &value_u8_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 value_s32 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &value_s32_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 value_u32 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &value_u32_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint64 value_s64 = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, &value_s64_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 value_u64 = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &value_u64_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool value_bool = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &value_bool_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float value_float = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(77u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &value_float_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double value_double = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(81u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &value_double_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value_string = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value_string()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value_string().data(), this->value_string().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bundle.Value.value_string"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes value_bytes = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_value_bytes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value_datetime = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value_datetime()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value_datetime().data(), this->value_datetime().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bundle.Value.value_datetime"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bundle.Value)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bundle.Value)
  return false;
#undef DO_
}

void Value::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bundle.Value)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .bundle.Value.ValueType type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // sint32 value_s8 = 2;
  if (this->value_s8() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(2, this->value_s8(), output);
  }

  // uint32 value_u8 = 3;
  if (this->value_u8() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->value_u8(), output);
  }

  // sint32 value_s32 = 4;
  if (this->value_s32() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(4, this->value_s32(), output);
  }

  // uint32 value_u32 = 5;
  if (this->value_u32() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->value_u32(), output);
  }

  // sint64 value_s64 = 6;
  if (this->value_s64() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(6, this->value_s64(), output);
  }

  // uint64 value_u64 = 7;
  if (this->value_u64() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(7, this->value_u64(), output);
  }

  // bool value_bool = 8;
  if (this->value_bool() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->value_bool(), output);
  }

  // float value_float = 9;
  if (this->value_float() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(9, this->value_float(), output);
  }

  // double value_double = 10;
  if (this->value_double() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->value_double(), output);
  }

  // string value_string = 11;
  if (this->value_string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value_string().data(), this->value_string().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bundle.Value.value_string");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->value_string(), output);
  }

  // bytes value_bytes = 12;
  if (this->value_bytes().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      12, this->value_bytes(), output);
  }

  // string value_datetime = 13;
  if (this->value_datetime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value_datetime().data(), this->value_datetime().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bundle.Value.value_datetime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      13, this->value_datetime(), output);
  }

  // @@protoc_insertion_point(serialize_end:bundle.Value)
}

::google::protobuf::uint8* Value::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:bundle.Value)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .bundle.Value.ValueType type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // sint32 value_s8 = 2;
  if (this->value_s8() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(2, this->value_s8(), target);
  }

  // uint32 value_u8 = 3;
  if (this->value_u8() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->value_u8(), target);
  }

  // sint32 value_s32 = 4;
  if (this->value_s32() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(4, this->value_s32(), target);
  }

  // uint32 value_u32 = 5;
  if (this->value_u32() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->value_u32(), target);
  }

  // sint64 value_s64 = 6;
  if (this->value_s64() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt64ToArray(6, this->value_s64(), target);
  }

  // uint64 value_u64 = 7;
  if (this->value_u64() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(7, this->value_u64(), target);
  }

  // bool value_bool = 8;
  if (this->value_bool() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->value_bool(), target);
  }

  // float value_float = 9;
  if (this->value_float() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(9, this->value_float(), target);
  }

  // double value_double = 10;
  if (this->value_double() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->value_double(), target);
  }

  // string value_string = 11;
  if (this->value_string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value_string().data(), this->value_string().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bundle.Value.value_string");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->value_string(), target);
  }

  // bytes value_bytes = 12;
  if (this->value_bytes().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        12, this->value_bytes(), target);
  }

  // string value_datetime = 13;
  if (this->value_datetime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value_datetime().data(), this->value_datetime().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bundle.Value.value_datetime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        13, this->value_datetime(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:bundle.Value)
  return target;
}

size_t Value::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bundle.Value)
  size_t total_size = 0;

  // string value_string = 11;
  if (this->value_string().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value_string());
  }

  // bytes value_bytes = 12;
  if (this->value_bytes().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->value_bytes());
  }

  // string value_datetime = 13;
  if (this->value_datetime().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value_datetime());
  }

  // .bundle.Value.ValueType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // sint32 value_s8 = 2;
  if (this->value_s8() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->value_s8());
  }

  // uint32 value_u8 = 3;
  if (this->value_u8() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->value_u8());
  }

  // sint32 value_s32 = 4;
  if (this->value_s32() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->value_s32());
  }

  // sint64 value_s64 = 6;
  if (this->value_s64() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt64Size(
        this->value_s64());
  }

  // uint32 value_u32 = 5;
  if (this->value_u32() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->value_u32());
  }

  // bool value_bool = 8;
  if (this->value_bool() != 0) {
    total_size += 1 + 1;
  }

  // uint64 value_u64 = 7;
  if (this->value_u64() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->value_u64());
  }

  // double value_double = 10;
  if (this->value_double() != 0) {
    total_size += 1 + 8;
  }

  // float value_float = 9;
  if (this->value_float() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Value::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bundle.Value)
  GOOGLE_DCHECK_NE(&from, this);
  const Value* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Value>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bundle.Value)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bundle.Value)
    MergeFrom(*source);
  }
}

void Value::MergeFrom(const Value& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bundle.Value)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value_string().size() > 0) {

    value_string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_string_);
  }
  if (from.value_bytes().size() > 0) {

    value_bytes_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_bytes_);
  }
  if (from.value_datetime().size() > 0) {

    value_datetime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_datetime_);
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.value_s8() != 0) {
    set_value_s8(from.value_s8());
  }
  if (from.value_u8() != 0) {
    set_value_u8(from.value_u8());
  }
  if (from.value_s32() != 0) {
    set_value_s32(from.value_s32());
  }
  if (from.value_s64() != 0) {
    set_value_s64(from.value_s64());
  }
  if (from.value_u32() != 0) {
    set_value_u32(from.value_u32());
  }
  if (from.value_bool() != 0) {
    set_value_bool(from.value_bool());
  }
  if (from.value_u64() != 0) {
    set_value_u64(from.value_u64());
  }
  if (from.value_double() != 0) {
    set_value_double(from.value_double());
  }
  if (from.value_float() != 0) {
    set_value_float(from.value_float());
  }
}

void Value::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bundle.Value)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Value::CopyFrom(const Value& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bundle.Value)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Value::IsInitialized() const {
  return true;
}

void Value::Swap(Value* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Value::InternalSwap(Value* other) {
  value_string_.Swap(&other->value_string_);
  value_bytes_.Swap(&other->value_bytes_);
  value_datetime_.Swap(&other->value_datetime_);
  std::swap(type_, other->type_);
  std::swap(value_s8_, other->value_s8_);
  std::swap(value_u8_, other->value_u8_);
  std::swap(value_s32_, other->value_s32_);
  std::swap(value_s64_, other->value_s64_);
  std::swap(value_u32_, other->value_u32_);
  std::swap(value_bool_, other->value_bool_);
  std::swap(value_u64_, other->value_u64_);
  std::swap(value_double_, other->value_double_);
  std::swap(value_float_, other->value_float_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Value::GetMetadata() const {
  protobuf_common_2fentity_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_common_2fentity_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Value

// .bundle.Value.ValueType type = 1;
void Value::clear_type() {
  type_ = 0;
}
::bundle::Value_ValueType Value::type() const {
  // @@protoc_insertion_point(field_get:bundle.Value.type)
  return static_cast< ::bundle::Value_ValueType >(type_);
}
void Value::set_type(::bundle::Value_ValueType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:bundle.Value.type)
}

// sint32 value_s8 = 2;
void Value::clear_value_s8() {
  value_s8_ = 0;
}
::google::protobuf::int32 Value::value_s8() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_s8)
  return value_s8_;
}
void Value::set_value_s8(::google::protobuf::int32 value) {
  
  value_s8_ = value;
  // @@protoc_insertion_point(field_set:bundle.Value.value_s8)
}

// uint32 value_u8 = 3;
void Value::clear_value_u8() {
  value_u8_ = 0u;
}
::google::protobuf::uint32 Value::value_u8() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_u8)
  return value_u8_;
}
void Value::set_value_u8(::google::protobuf::uint32 value) {
  
  value_u8_ = value;
  // @@protoc_insertion_point(field_set:bundle.Value.value_u8)
}

// sint32 value_s32 = 4;
void Value::clear_value_s32() {
  value_s32_ = 0;
}
::google::protobuf::int32 Value::value_s32() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_s32)
  return value_s32_;
}
void Value::set_value_s32(::google::protobuf::int32 value) {
  
  value_s32_ = value;
  // @@protoc_insertion_point(field_set:bundle.Value.value_s32)
}

// uint32 value_u32 = 5;
void Value::clear_value_u32() {
  value_u32_ = 0u;
}
::google::protobuf::uint32 Value::value_u32() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_u32)
  return value_u32_;
}
void Value::set_value_u32(::google::protobuf::uint32 value) {
  
  value_u32_ = value;
  // @@protoc_insertion_point(field_set:bundle.Value.value_u32)
}

// sint64 value_s64 = 6;
void Value::clear_value_s64() {
  value_s64_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 Value::value_s64() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_s64)
  return value_s64_;
}
void Value::set_value_s64(::google::protobuf::int64 value) {
  
  value_s64_ = value;
  // @@protoc_insertion_point(field_set:bundle.Value.value_s64)
}

// uint64 value_u64 = 7;
void Value::clear_value_u64() {
  value_u64_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 Value::value_u64() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_u64)
  return value_u64_;
}
void Value::set_value_u64(::google::protobuf::uint64 value) {
  
  value_u64_ = value;
  // @@protoc_insertion_point(field_set:bundle.Value.value_u64)
}

// bool value_bool = 8;
void Value::clear_value_bool() {
  value_bool_ = false;
}
bool Value::value_bool() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_bool)
  return value_bool_;
}
void Value::set_value_bool(bool value) {
  
  value_bool_ = value;
  // @@protoc_insertion_point(field_set:bundle.Value.value_bool)
}

// float value_float = 9;
void Value::clear_value_float() {
  value_float_ = 0;
}
float Value::value_float() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_float)
  return value_float_;
}
void Value::set_value_float(float value) {
  
  value_float_ = value;
  // @@protoc_insertion_point(field_set:bundle.Value.value_float)
}

// double value_double = 10;
void Value::clear_value_double() {
  value_double_ = 0;
}
double Value::value_double() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_double)
  return value_double_;
}
void Value::set_value_double(double value) {
  
  value_double_ = value;
  // @@protoc_insertion_point(field_set:bundle.Value.value_double)
}

// string value_string = 11;
void Value::clear_value_string() {
  value_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Value::value_string() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_string)
  return value_string_.GetNoArena();
}
void Value::set_value_string(const ::std::string& value) {
  
  value_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bundle.Value.value_string)
}
#if LANG_CXX11
void Value::set_value_string(::std::string&& value) {
  
  value_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bundle.Value.value_string)
}
#endif
void Value::set_value_string(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bundle.Value.value_string)
}
void Value::set_value_string(const char* value, size_t size) {
  
  value_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bundle.Value.value_string)
}
::std::string* Value::mutable_value_string() {
  
  // @@protoc_insertion_point(field_mutable:bundle.Value.value_string)
  return value_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Value::release_value_string() {
  // @@protoc_insertion_point(field_release:bundle.Value.value_string)
  
  return value_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Value::set_allocated_value_string(::std::string* value_string) {
  if (value_string != NULL) {
    
  } else {
    
  }
  value_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value_string);
  // @@protoc_insertion_point(field_set_allocated:bundle.Value.value_string)
}

// bytes value_bytes = 12;
void Value::clear_value_bytes() {
  value_bytes_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Value::value_bytes() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_bytes)
  return value_bytes_.GetNoArena();
}
void Value::set_value_bytes(const ::std::string& value) {
  
  value_bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bundle.Value.value_bytes)
}
#if LANG_CXX11
void Value::set_value_bytes(::std::string&& value) {
  
  value_bytes_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bundle.Value.value_bytes)
}
#endif
void Value::set_value_bytes(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bundle.Value.value_bytes)
}
void Value::set_value_bytes(const void* value, size_t size) {
  
  value_bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bundle.Value.value_bytes)
}
::std::string* Value::mutable_value_bytes() {
  
  // @@protoc_insertion_point(field_mutable:bundle.Value.value_bytes)
  return value_bytes_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Value::release_value_bytes() {
  // @@protoc_insertion_point(field_release:bundle.Value.value_bytes)
  
  return value_bytes_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Value::set_allocated_value_bytes(::std::string* value_bytes) {
  if (value_bytes != NULL) {
    
  } else {
    
  }
  value_bytes_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value_bytes);
  // @@protoc_insertion_point(field_set_allocated:bundle.Value.value_bytes)
}

// string value_datetime = 13;
void Value::clear_value_datetime() {
  value_datetime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Value::value_datetime() const {
  // @@protoc_insertion_point(field_get:bundle.Value.value_datetime)
  return value_datetime_.GetNoArena();
}
void Value::set_value_datetime(const ::std::string& value) {
  
  value_datetime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bundle.Value.value_datetime)
}
#if LANG_CXX11
void Value::set_value_datetime(::std::string&& value) {
  
  value_datetime_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bundle.Value.value_datetime)
}
#endif
void Value::set_value_datetime(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_datetime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bundle.Value.value_datetime)
}
void Value::set_value_datetime(const char* value, size_t size) {
  
  value_datetime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bundle.Value.value_datetime)
}
::std::string* Value::mutable_value_datetime() {
  
  // @@protoc_insertion_point(field_mutable:bundle.Value.value_datetime)
  return value_datetime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Value::release_value_datetime() {
  // @@protoc_insertion_point(field_release:bundle.Value.value_datetime)
  
  return value_datetime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Value::set_allocated_value_datetime(::std::string* value_datetime) {
  if (value_datetime != NULL) {
    
  } else {
    
  }
  value_datetime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value_datetime);
  // @@protoc_insertion_point(field_set_allocated:bundle.Value.value_datetime)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

Entity::Entity_ValuesEntry::Entity_ValuesEntry() {}
Entity::Entity_ValuesEntry::Entity_ValuesEntry(::google::protobuf::Arena* arena) : SuperType(arena) {}
::google::protobuf::Metadata Entity::Entity_ValuesEntry::GetMetadata() const {
  protobuf_common_2fentity_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_common_2fentity_2eproto::file_level_metadata[1];
}
void Entity::Entity_ValuesEntry::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}
void Entity::Entity_ValuesEntry::MergeFrom(const Entity_ValuesEntry& other) {
  MergeFromInternal(other);
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Entity::kIdFieldNumber;
const int Entity::kValuesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Entity::Entity()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_common_2fentity_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:bundle.Entity)
}
Entity::Entity(const Entity& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  values_.MergeFrom(from.values_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:bundle.Entity)
}

void Entity::SharedCtor() {
  id_ = GOOGLE_ULONGLONG(0);
  _cached_size_ = 0;
}

Entity::~Entity() {
  // @@protoc_insertion_point(destructor:bundle.Entity)
  SharedDtor();
}

void Entity::SharedDtor() {
}

void Entity::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Entity::descriptor() {
  protobuf_common_2fentity_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_common_2fentity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Entity& Entity::default_instance() {
  protobuf_common_2fentity_2eproto::InitDefaults();
  return *internal_default_instance();
}

Entity* Entity::New(::google::protobuf::Arena* arena) const {
  Entity* n = new Entity;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Entity::Clear() {
// @@protoc_insertion_point(message_clear_start:bundle.Entity)
  values_.Clear();
  id_ = GOOGLE_ULONGLONG(0);
}

bool Entity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bundle.Entity)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, .bundle.Value> values = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          Entity_ValuesEntry::Parser< ::google::protobuf::internal::MapField<
              Entity_ValuesEntry,
              ::std::string, ::bundle::Value,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::std::string, ::bundle::Value > > parser(&values_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), parser.key().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bundle.Entity.ValuesEntry.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bundle.Entity)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bundle.Entity)
  return false;
#undef DO_
}

void Entity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bundle.Entity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->id(), output);
  }

  // map<string, .bundle.Value> values = 2;
  if (!this->values().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::bundle::Value >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), p->first.length(),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "bundle.Entity.ValuesEntry.key");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->values().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->values().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::bundle::Value >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::bundle::Value >::const_iterator
          it = this->values().begin();
          it != this->values().end(); ++it, ++n) {
        items[n] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[n], Less());
      ::google::protobuf::scoped_ptr<Entity_ValuesEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(values_.NewEntryWrapper(
            items[i]->first, items[i]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
        Utf8Check::Check(items[i]);
      }
    } else {
      ::google::protobuf::scoped_ptr<Entity_ValuesEntry> entry;
      for (::google::protobuf::Map< ::std::string, ::bundle::Value >::const_iterator
          it = this->values().begin();
          it != this->values().end(); ++it) {
        entry.reset(values_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  // @@protoc_insertion_point(serialize_end:bundle.Entity)
}

::google::protobuf::uint8* Entity::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:bundle.Entity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->id(), target);
  }

  // map<string, .bundle.Value> values = 2;
  if (!this->values().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::bundle::Value >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), p->first.length(),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "bundle.Entity.ValuesEntry.key");
      }
    };

    if (deterministic &&
        this->values().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->values().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::bundle::Value >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::bundle::Value >::const_iterator
          it = this->values().begin();
          it != this->values().end(); ++it, ++n) {
        items[n] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[n], Less());
      ::google::protobuf::scoped_ptr<Entity_ValuesEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(values_.NewEntryWrapper(
            items[i]->first, items[i]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
        Utf8Check::Check(items[i]);
      }
    } else {
      ::google::protobuf::scoped_ptr<Entity_ValuesEntry> entry;
      for (::google::protobuf::Map< ::std::string, ::bundle::Value >::const_iterator
          it = this->values().begin();
          it != this->values().end(); ++it) {
        entry.reset(values_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  // @@protoc_insertion_point(serialize_to_array_end:bundle.Entity)
  return target;
}

size_t Entity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bundle.Entity)
  size_t total_size = 0;

  // map<string, .bundle.Value> values = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->values_size());
  {
    ::google::protobuf::scoped_ptr<Entity_ValuesEntry> entry;
    for (::google::protobuf::Map< ::std::string, ::bundle::Value >::const_iterator
        it = this->values().begin();
        it != this->values().end(); ++it) {
      entry.reset(values_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  // uint64 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Entity::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bundle.Entity)
  GOOGLE_DCHECK_NE(&from, this);
  const Entity* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Entity>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bundle.Entity)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bundle.Entity)
    MergeFrom(*source);
  }
}

void Entity::MergeFrom(const Entity& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bundle.Entity)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  values_.MergeFrom(from.values_);
  if (from.id() != 0) {
    set_id(from.id());
  }
}

void Entity::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bundle.Entity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Entity::CopyFrom(const Entity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bundle.Entity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Entity::IsInitialized() const {
  return true;
}

void Entity::Swap(Entity* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Entity::InternalSwap(Entity* other) {
  values_.Swap(&other->values_);
  std::swap(id_, other->id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Entity::GetMetadata() const {
  protobuf_common_2fentity_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_common_2fentity_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Entity

// uint64 id = 1;
void Entity::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 Entity::id() const {
  // @@protoc_insertion_point(field_get:bundle.Entity.id)
  return id_;
}
void Entity::set_id(::google::protobuf::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:bundle.Entity.id)
}

// map<string, .bundle.Value> values = 2;
int Entity::values_size() const {
  return values_.size();
}
void Entity::clear_values() {
  values_.Clear();
}
 const ::google::protobuf::Map< ::std::string, ::bundle::Value >&
Entity::values() const {
  // @@protoc_insertion_point(field_map:bundle.Entity.values)
  return values_.GetMap();
}
 ::google::protobuf::Map< ::std::string, ::bundle::Value >*
Entity::mutable_values() {
  // @@protoc_insertion_point(field_mutable_map:bundle.Entity.values)
  return values_.MutableMap();
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace bundle

// @@protoc_insertion_point(global_scope)
